name: STG/Deploy

on:
  push:
    branches:
      - hackaton-2021

jobs:
  call-shared-deployment-workflow:
    name: "."
    uses: agendrix/hello-pdf/.github/workflows/shared-deploy.yml@hackaton-2021
    secrets:
      aws_access_key_id: ${{ secrets.STAGING_AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.STAGING_AWS_SECRET_ACCESS_KEY }}
      aws_account_id: ${{ secrets.STAGING_AWS_ACCOUNT_ID }}
      ssh_key: ${{ secrets.SSH_KEY }}
      slack_lambda_endpoint: ${{ secrets.STAGING_SLACK_LAMBDA_ENDPOINT }}
      slack_api_secret: ${{ secrets.STAGING_SLACK_API_SECRET }}
