name: Tests

on: push

jobs:
  test-js:
    name: Test Javascript
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Test
        run: yarn test

  test-ruby:
    name: Test Ruby
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'

      - name: Install dependencies
        run: bundle install

      - name: Test
        run: bundle exec rake test
